#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app



FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["CsmsAPI/CsmsAPI.csproj", "CsmsAPI/"]
COPY ["Domain.Configration/Domain.Configration.csproj", "Domain.Configration/"]
COPY ["Domain.Entities/Domain.Entities.csproj", "Domain.Entities/"]
COPY ["Infrastructure.Configration/Infrastructure.Configration.csproj", "Infrastructure.Configration/"]
COPY ["Persistence.Repository/Persistence.Repository.csproj", "Persistence.Repository/"]
COPY ["Persistence.IRepository/Persistence.IRepository.csproj", "Persistence.IRepository/"]
COPY ["Infrastructure.ViewModel/Infrastructure.ViewModel.csproj", "Infrastructure.ViewModel/"]
COPY ["Infrastructure.Executed/Infrastructure.Executed.csproj", "Infrastructure.Executed/"]
COPY ["Service.Data/Service.Data.csproj", "Service.Data/"]
COPY ["Service.Interface/Service.Interface.csproj", "Service.Interface/"]
RUN dotnet restore "CsmsAPI/CsmsAPI.csproj"
COPY . .
WORKDIR "/src/CsmsAPI"
RUN dotnet build "CsmsAPI.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "CsmsAPI.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
EXPOSE 80
EXPOSE 443
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "CsmsAPI.dll"]